### ISSUE TITLE
Android compatibility regression in v0.20 and v0.21

### ISSUE THREAD

**Issue by mingfai** [headissue/cache2k#19]
v0.19.2 works fine on Android, but the Cache2k v.20 and v0.21 result as the following error:
```
java.lang.Error: cache2k implementation not found, cache2k-core.jar missing? 
	at org.cache2k.CacheManager.implNotFound(CacheManager.java:91) 
 	at org.cache2k.CacheManager.getInstance(CacheManager.java:84)
```

the dependency is defined in gradle as follows
```
    compile 'org.cache2k:cache2k-api:0.21'
    compile 'org.cache2k:cache2k-core:0.21'//runtime
```
(the test is done without proguard)

**Comment by cruftex** [comment]
Thanks for reporting! Fixing this ASAP.

**Comment by cruftex** [comment]
Pinpointed the problem source, full stack trace:

java.lang.Error: cache2k implementation not found, cache2k-core.jar missing?
at org.cache2k.CacheManager.implNotFound(CacheManager.java:91)
at org.cache2k.CacheManager.getInstance(CacheManager.java:84)
at org.cache2k.impl.CacheBuilderImpl.build(CacheBuilderImpl.java:171)
at org.cache2k.test.BasicCacheTest.testPeekAndPut(BasicCacheTest.java:38)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)
Caused by: java.lang.NullPointerException
at org.cache2k.impl.CacheManagerImpl.<init>(CacheManagerImpl.java:92)
at org.cache2k.impl.CacheManagerImpl.<init>(CacheManagerImpl.java:82)
at java.lang.Class.newInstanceImpl(Native Method)
at java.lang.Class.newInstance(Class.java:1319)
at org.cache2k.CacheManager.getInstance(CacheManager.java:82)
... 14 more

**Comment by cruftex** [comment]
Just checked, running CI tests on the Android emulator seems still beta on Travis CI:
http://docs.travis-ci.com/user/languages/android/

**Comment by cruftex** [comment]
Version 0.21.1 is released which fixes the issue.
